Added docker hub credentials during build process to prevent pull rate limit from the dockerhub

diff --git a/k8-buildspec.yml b/k8-buildspec.yml
--- a/k8-buildspec.yml
+++ b/k8-buildspec.yml
@@ -16,11 +16,22 @@ phases:
       commands:
         
         # Retrieve Docker credentials from Secrets Manager
+        # Check the full secret to ensure the structure is correct
+        - aws secretsmanager get-secret-value --secret-id $DOCKER_HUB_CREDENTIALS --query 'SecretString' --output text
         - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id $DOCKER_HUB_CREDENTIALS --query 'SecretString' --output text | jq -r .username)
         - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id $DOCKER_HUB_CREDENTIALS --query 'SecretString' --output text | jq -r .password)
+        # Debugging: Verify the values are being set correctly
+          echo "Docker username from secrets: $DOCKER_USERNAME"
+          echo "DOCKER_PASSWORD is set"
+
+        # Check if the password is empty
+          if [ -z "$DOCKER_PASSWORD" ]; then
+          echo "Error: DOCKER_PASSWORD is empty"
+          exit 1
+          fi  
         - echo "Docker username from secrets: $DOCKER_USERNAME"
         - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-        - echo "Docker login successful - ${BRANCH}"
+        - echo "Docker login successful"
         - TAG="$CODEBUILD_BUILD_NUMBER.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
         - echo $TAG
         - sed -i.bak -e 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' kubernetes/k8-deployment.yaml
